### ISSUE TITLE
Doesn't work on local html files.

### ISSUE THREAD

**Issue by sephiron99** [jacojang/jjDicTrans#1]
하드디스크 등에 저장된 로컬 html 파일에서는 동작하지 않네요.

**Comment by jacojang** [comment]
Local 파일을 테스트 해보지 못했는데 실제로 해보니 말씀하신대로 동작하지 않네요. 어떤 문제인지 확인해 보도록 하겠습니다. 감사합니다.

**Comment by jacojang** [comment]
sdk/page-mod 가 Local 파일일 경우에는 동작을 하지 않네요. 작업이 좀 복잡해 질수도 있겠네요.
