### ISSUE TITLE
popup위치 설정 버그

### ISSUE THREAD

**Issue by ghost** [jacojang/jjDicTrans#3]
파이어폭스 45.0.1 64비트 사용 중
우측 상단의 jjdictrans 아이콘을 누르면

마지막 옵션에 Popup위치라고 된 부분에서

우측상단
커서위치
이 두 개 중 하나의 설정 값을 지정할 수 있는데

여기서 커서위치를 선택하고
파이어폭스를 종료하고, 파이어폭스를 다시 시작해서
다시 아이콘을 눌러서 설정 값을 볼 때
커서위치로 선택했음에도 불구하고 우측상단으로 설정된 것으로 표시됨.
그러나 실제로는 커서위치로 정상적으로 사용됨.

단순한 표기에만 버그가 있음

**Comment by jacojang** [comment]
네~ 확인해 보도록 하겠습니다. 감사합니다.

**Comment by jacojang** [comment]
0.5.4 버전에서 해당 문제 수정 했습니다.
